spring:
  datasource:
    url: jdbc:sqlite:./bing-wallpaper.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  task:
    scheduling:
      pool:
        size: 5   # 定时任务线程池大小
      shutdown:
        await-termination: true
        await-termination-period: 30s
task:
  wallpaper:
    cron: "0 0 */1 * * ?"
    enable: false
