server:
  port: 9123
  servlet:
    context-path: /api

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  datasource:
    url: jdbc:sqlite:./bing-wallpaper.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
  task:
    scheduling:
      pool:
        size: 5   # 定时任务线程池大小
      shutdown:
        await-termination: true
        await-termination-period: 30s

mybatis:
  mapper-locations: classpath:com/shimu/wallpaper/api/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印sql日志

knife4j:
  enable: true
  setting:
    language: zh-CN
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "Wallpaper API"
        url: /v3/api-docs

task:
  wallpaper:
    cron: "0 0 */1 * * ?"
    enable: true

mirror:
  github:
    - https://hub.gitmirror.com/raw.githubusercontent.com