server:
  port: 9123
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:sqlite:./bing-wallpaper.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect